#ifndef BLOCK_DEVICE_H_INCLUDED
#define BLOCK_DEVICE_H_INCLUDED

/** @file */

#include "devices/abstract_device.h"

#ifndef BLOCKSIG
#define BLOCKSIG SIGRTMIN + 1
#endif

class BlockDevice: public AbstractDevice {

	public:
		BlockDevice();
		~BlockDevice();

		void setTimer(int usec);
		void disarm();
};

/** \def BLOCKSIG
 *	Signal generated by BlockDevice
 */

#endif // BLOCK_DEVICE_H_INCLUDED
