#ifndef CHAR_DEVICE_H_INCLUDED
#define CHAR_DEVICE_H_INCLUDED

/** @file */

#include "devices/abstract_device.h"

#ifndef CHARSIG
#define CHARSIG SIGRTMIN + 2
#endif

class CharDevice: public AbstractDevice {
	public:
		CharDevice();
		~CharDevice();

		void setTimer(int usec);
		void disarm();
};

/** \def CHARSIG
 *	Signal generated by CharDevice
 */

#endif // CHAR_DEVICE_H_INCLUDED
