#ifndef CHAR_DEVICE_H_INCLUDED
#define CHAR_DEVICE_H_INCLUDED

/** @file */

#include <queue>
#include "devices/queued_device.h"

#ifndef CHARSIG
#define CHARSIG SIGRTMIN + 2
#endif

using namespace std;

class cCharDevice: public cAbsQueuedDevice {
	private:
		/// @cond
		timer_t timerid;
		struct sigevent sev;
		struct itimerspec iTime;
		/// @endcond

		queue<ProcessInfo*> waitQueue;

		pthread_mutex_t deviceLock;

	public:
		cCharDevice(int usec);
		~cCharDevice();

		void setDefaultTime(int usec);
		void scheduleDevice(ProcessInfo*);

		ProcessInfo* timerFinished();

		int queueLength();
};

/** \def CHARSIG
 *	Signal generated by CharDevice
 */

#endif // CHAR_DEVICE_H_INCLUDED
