5103 Project 2: cPRPolicy Class Reference
cPRPolicy Class Reference
Abstract Page Replacement Policy.
#include <pageReplace.h>
Public Member Functions
cPRPolicy (cFrameAllocPolicy &)
virtual const char * name ()=0
Name of PR module.
virtual ePRStatus resolvePageFault (sProc *proc, uint32_t page)=0
Get a page frame for this process.
ePRStatus resolveCircularPF (sProc *proc, uint32_t page)
virtual void finishedQuanta (sProc *)=0
This is called after an execution quanta finishes.
virtual void finishedIO (sProc *, sPTE *)=0
This is called after an I/O (input) completes.
virtual bool clearPages (int numPages)=0
Remove this many pages from memory.
virtual void unpinFrame (uint32_t frame)=0
This is typically called after ::finishedIO so that the PR module unpins the frame in the frame allocation module.
virtual void returnFrame (uint32_t frame)=0
Return this frame to the system.
Member Function Documentation
cPRPolicy::clearPages (int numPages) [pure virtual]
If the cleaning daemon decides that pages need to be cleaned it will determine how many from its policy and call the PR module to clean that many. This method keeps the PR policy separate from the decision on how many pages to clean and when.
Parameters:
int Number of pages to clear.
Implemented in cPRLru, cPRLruApprox, and cPRFifo.
Referenced by cVMM::start().
cPRPolicy::finishedIO (sProc * , sPTE *) [pure virtual]
This is another notification point for the PR module to update its data structs.
Implemented in cPRLru, cPRLruApprox, and cPRFifo.
Referenced by cVMM::start().
cPRPolicy::finishedQuanta (sProc *) [pure virtual]
This gives the PR module a chance to update its internal data-structures using the reference bits or any other data available from the process struct.
Implemented in cPRLru, cPRLruApprox, and cPRFifo.
Referenced by cVMM::start().
virtual const char* cPRPolicy::name () [pure virtual]
This is only used for logging purposes so that the PR module can be easily identified.
Implemented in cPRLruApprox, cPRLru, and cPRFifo.
Referenced by cVMM::printResults().
virtual ePRStatus cPRPolicy::resolvePageFault (sProc * proc, uint32_t page) [pure virtual]
If a free one is available from the frame allocator it will be used. Otherwise, a page will have to be spilled.
Parameters:
sProc* A pointer to the process that the frame is being requested for.
uint32_t page The page for the given process that needs to be fetched.
Implemented in cPRLru, cPRLruApprox, and cPRFifo.
Referenced by cVMM::start().
cPRPolicy::returnFrame (uint32_t frame) [pure virtual]
This is called when a process exits and its frames are being returned to the system. This is usually a wrapper to the FA policy return frame function but it gives the PR module a chance to update its datastructures if necessary.
Since we have made the assumption that this is only called on process exit, it is not necessary to do any I/O on the page.
Parameters:
uint32_t Number of the frame to clear/return.
Implemented in cPRLru, cPRLruApprox, and cPRFifo.
Referenced by cVMM::cleanupProcess().
The documentation for this class was generated from the following files:
include/Policy/pageReplace.h
src/Policy/pageReplace.cpp