5103 Project 2: cIOControl Class Reference
cIOControl Class Reference
Class representing an I/O controller.
#include <io_control.h>
Public Member Functions
cIOControl (int numProcs, int *VC)
Reference virtual counter in core.
queue< uint64_t > & getFinishedQueue ()
Get a reference to the finished queue.
queue< sPTE * > & getFinishedPTEQueue ()
Get a reference to the finished PTE queue.
void tick ()
Count 1 time unit.
void tick (int times)
This executes ::tick() N number of times.
sIOContext * scheduleIO (sProc *proc, uint32_t page, eIOType iotype, sIOContext *release=NULL)
Schedule an I/O event.
Private Member Functions
void removeWait (uint32_t)
Remove an I/O context from waiting.
sIOContext * getContext ()
Get a context struct.
void returnContext (sIOContext *ctx)
Return a context struct for future use.
void dumpIOError (sProc *)
Generate and throw IO Error.
Private Attributes
int io_req_time
int io_time
vector< queue< sIOContext * > > io_out
What is being paged out?
vector< queue< sIOContext * >
>::iterator out_iter
queue< sIOContext * > io_in
What is the next page in?
vector< sIOContext * > io_in_wait
I/O in requests waiting for an io_out to finish.
vector< sIOContext * >::iterator in_wait_iter
queue< sIOContext * > context_cache
Cache of previously allocated contexts.
queue< uint64_t > finished
Queue that holds process ids that have completed and I/O.
queue< sPTE * > finishedPTE
Holds the PTE of finished I/O in's.
int * VC
Member Function Documentation
cIOControl::dumpIOError (sProc * proc) [private]
This does the work of generating an IO excetion.It was originally intended to work broadly for many different scenarios but the necessity was not there. It works but it produces a fairly generic error.
Referenced by scheduleIO().
cIOControl::getContext () [private]
If there is a context struct cached from previous use then it is returned. Otherwise a new one is allocated.
Referenced by scheduleIO().
cIOControl::getFinishedPTEQueue () [inline]
This is called by the core to get a reference to this specific queue to be used in processing finished I/O. The purpose for this queue was that the VMM core needed the frame of the completed I/O so it could be unpinned. Given the PTE in this queue it makes page data in the finished queue redundant.
Referenced by cVMM::start().
cIOControl::getFinishedQueue () [inline]
This is called by the core to get a refernce to this specific queue so it can be used in processing finished I/O. This queue hold 64-bit integers representing the pid and page of for the completed I/O.
Referenced by cVMM::start().
cIOControl::removeWait (uint32_t pid) [private]
When an I/O out completes, if its release context property is not null then the controller will try to release the specified context from the waiting vector.
Referenced by tick().
cIOControl::returnContext (sIOContext * ctx) [private]
The struct is not deallocated. It is put into a cache queue.
Referenced by tick().
cIOControl::scheduleIO (sProc * proc, uint32_t page, eIOType iotype, sIOContext * release = NULL)
Schedule I/O.
This is used to schedule some I/O. The type is specified by the eIOType parameter. If the type is eIOType::IO_IN_WAIT it will be put in a vector (indexed by pid) waiting to be released. If the type is eIOType::IO_OUT and the sIOContext* != NULL then after the I/O completes it will relese the I/O pointed to by this context.
Referenced by cVMM::pageIn(), and cVMM::pageOut().
cIOControl::tick ()
Thiscounts 1 virtual time unite and modifies the remaining time on pending I/O correspondingly.
Referenced by scheduleIO(), cVMM::start(), tick(), and cVMM::tickController().
cIOControl::tick (int times)
This is useful in recording virtual time with events that take chunks of time such as the context switching of a process.
Parameters:
int Number of ticks to execute.
Member Data Documentation
queue<sIOContext*> cIOControl::context_cache [private]
This is simply a performance boost to avoid constantly allocating/deallocating context structs.
Referenced by getContext(), and returnContext().
queue<uint64_t> cIOControl::finished [private]
This is specifically used for completed page ins. After calling tick, any completed processes are placed in here and the VMM core can read it and unblock.
I made it a 64-bit data type so that I didn't need to mess with allocating and managing some other structure. The first 32-bits represent the pid of the process whose I/O completed. The last 32-bits is the page that was brought in for the process. From this the core can get the frame and unpin it.
Referenced by tick().
queue<sIOContext*> cIOControl::io_in [private]
This keeps track of the next page to complete its I/O.
Referenced by removeWait(), scheduleIO(), and tick().
vector<queue<sIOContext*> > cIOControl::io_out [private]
This vector is indexed by pid and it holds a queue of the pages of the respective process which are being paged out. This is so that in the case that a process has a page spilled by some other process' page fault or the cleaning daemon, it is prevented from recovering the page until it is successfully written out.
Referenced by cIOControl(), scheduleIO(), and tick().
The documentation for this class was generated from the following files:
include/io_control.h
src/io_control.cpp