5103 Project 2: cMMU Class Reference
cMMU Class Reference
Class representing an MMU in the CPU.
#include <mmu.h>
Public Member Functions
void setPTBR (sPTE *_ptbr)
Set the Page Table Base Register.
void addVC (int *VC)
Add a refernece to the main VCC for timekeeping purposes.
void flushTLB (bool sync=true)
Flush the tlb and optionally sync values back to page table.
void syncTLB ()
Sync TLB entries without flushing them.
eMMUstate checkStatus ()
What is the MMU status after the last translation.
uint32_t getFaultPage ()
What was the VPN that caused the fault.
uint32_t getAddr (string &sVA, bool isWrite)
Translate virtual to physical address.
Private Member Functions
void addTLB (uint32_t, uint32_t, bool)
Add an entry to the TLB.
Private Attributes
sTLBE * TLB
uint16_t tlbSize
uint32_t pageSize
uint32_t off_bits
bool hexAddr
stringstream ssAddr
uint32_t replaceIndex
For replacing old tlb entries we are simply treating it as a ring buffer.
int * VC
sPTE * ptbr
int tlb_hits
int tlb_misses
eMMUstate mmu_status
uint32_t faultPage
Member Function Documentation
cMMU::checkStatus () [inline]
Since the getAddr function returns the translated address. With the exception of doing some bit packing we can't return the status in the same variable.
Referenced by cCPU::run().
cMMU::flushTLB (bool sync = true)
On context switch this is called to clear all the entries by simply setting their valid bit to false. If the sync flag is set and a page is dirty/referenced then this information is written back to the main page table.
This syncing is usually not necessary since the cpu calls sync on a page fault or quanta terminnation so that the table is up-to-date for the PR module to make decisions.
Referenced by cCPU::switchProc().
uint32_t cMMU::getAddr (string & sVA, bool isWrite)
This method checks the tlb and page table simultaneously and returns the appropriate address. Whoever receives this should first check the mmu status to make sure it is valid.
Parameters:
bool write If set, the mmu will mark this page as dirty.
Referenced by cCPU::run().
cMMU::getFaultPage () [inline]
The cpu calls this to send back to the VMM core so it can handle it accordingly.
Referenced by cCPU::getFaultPage().
cMMU::setPTBR (sPTE * _ptbr) [inline]
This needs to be reset on context switch
Referenced by cCPU::switchProc().
cMMU::syncTLB ()
This is the same as ::fulshTLB with the exception of not flushing/ invalidating the table entries. This is useful when an execution quanta finishes so you want to sync the entries but not flush them in-case it is the only process left.
Referenced by cCPU::run().
Member Data Documentation
uint32_t cMMU::replaceIndex [private]
This is the index where new entries are being placed
Referenced by addTLB(), and flushTLB().
The documentation for this class was generated from the following files:
include/mmu.h
src/mmu.cpp