5103 Project 1: cKernel Class Reference
cKernel Class Reference
Core managing class for this simulated OS.
#include <kernel.h>
Public Member Functions
cKernel (cScheduler &)
Default cKernel constructor.
void boot ()
Start the 'OS' Kernel.
void initProcess (const char *filename, pidType parent, int priority=DEFAULT_PRIORITY)
Initialize a Process.
void cleanupProcess (pidType pid)
Cleans up a terminated process.
Private Member Functions
void swapProcesses (ProcessInfo *proc, bool switchMode=true)
Swap a process on the cpu.
void cleanupProcess (ProcessInfo *)
Cleanup process memory and state.
void sigHandler (int signum, siginfo_t *info)
Handler for all signals.
Static Private Member Functions
static void sig_catch (int signum, siginfo_t *info, void *context)
Static function just for capturing signals.
Private Attributes
FILE * traceStream
cProcessLogger procLogger
cCPU cpu
int clockTick
pthread_mutex_t intLock
Lock for condition variable.
pthread_cond_t intCond
For synchronization with clocktick.
cBlockDevice bDevice
cCharDevice cDevice
ClockDevice clockInterrupt
pthread_t deviceThread
sem_t DevSigSem
A device interrupt has been received.
sem_t BSigSem
A block device interrupt has been received.
sem_t CSigSem
A char device interrupt has been received.
ProcessInfo * runningProc
Process currently on the cpu.
cIDManager idGenerator
For generating new process PID's.
cScheduler & scheduler
Static Private Attributes
static cKernel * kernel_instance
Friends
void * deviceHandle (void *)
Thread function for handline device interrupts.
Constructor & Destructor Documentation
cKernel::cKernel (cScheduler & s)
The default constructor initializes all internal datastructures and loads the initial program (default: 'main.trace') but does not run it.
Member Function Documentation
void cKernel::boot ()
Starts the main kernel loop. The initial program is loaded and execution follows from there.
Exceptions:
kernelError
void cKernel::cleanupProcess (ProcessInfo * proc) [private]
This is called when a process is being removed from the system and its memory and any remaining state information needs to be cleaned up.
Referenced by boot().
void cKernel::cleanupProcess (pidType pid)
Cleans up any memory and kernel entries associated with the terminated process. Also removes the process from the scheduler.
void cKernel::initProcess (const char * filename, pidType parent, int priority = DEFAULT_PRIORITY)
Initializes a process by loading program file contents, setting default process values and adding it in a ready state to the scheduler.
Referenced by boot(), and cKernel().
void cKernel::sigHandler (int signum, siginfo_t * info) [private]
For clock interrupt signals, the handler signals on a condition variable which the main thread will be waiting on.
For block and character devices, the appropriate semaphores are incremented which will unblock the waiting thread to act on them.
This function is called by cKernel::sig_catch
See also:
deviceHandle(void*)
cKernel::intCond
DevSigSem
CSigSem
BSigSem
Referenced by sig_catch().
void cKernel::swapProcesses (ProcessInfo * proc, bool switchMode = true) [private]
Takes the process in its parameter and swaps it with the one currently running in the cpu.
Referenced by boot().
Friends And Related Function Documentation
void* deviceHandle (void * args) [friend]
Since limited work can be done within the signal handlers and the main thread may block, a separate thread must be present to handle device interrupts.
See also:
DevSigSem
CSigSem
BSigSem
Parameters:
void* This is a pointer to the kernel instance.
Referenced by boot().
The documentation for this class was generated from the following files:
include/kernel.h
src/kernel.cpp