5103 Project 2: cException Class Reference
cException Class Reference
Generic exception class.
#include <exceptions.h>
Public Member Functions
void setErrorStr (const string &msg)
void setFatality (bool f)
Is this a fatal error?
string & getErrorStr ()
bool isFatal ()
Private Attributes
string errMsg
bool fatal
Detailed Description
These exceptions are caught in main and their error messages are printed out.
Member Function Documentation
void cException::setFatality (bool f) [inline]
After this is set you must press up, up, down, down, left, right, left, right, B, A. Hopefully then the program will fix itself. No really, you should end the program.
Referenced by cPRFifo::clearPages(), cPRLruApprox::clearPages(), and cPRLru::clearPages().
The documentation for this class was generated from the following file:
include/exceptions.h