5103 Project 1: cScheduler Class Reference
cScheduler Class Reference
Abstract Interface for Schedulers.
#include <scheduler.h>
Public Member Functions
virtual void initProcScheduleInfo (ProcessInfo *)=0
Initialize scheduler specific information within the ProcessInfo struct.
virtual void addProcess (ProcessInfo *)=0
Transfer control of process state and scheduling.
virtual void setBlocked (ProcessInfo *)=0
Set a process into a blocked state.
virtual void unblockProcess (ProcessInfo *)=0
Unblock a process and make it ready.
virtual void removeProcess (ProcessInfo *)=0
Remove a process from the control of the scheduler.
virtual ProcessInfo * getNextToRun ()=0
Query the scheduler for next process to run.
virtual pidType numProcesses ()=0
How many processes are in the scheduler.
virtual void addLogger (FILE *)=0
Add an instance of the trace logger to the scheduler.
virtual void addProcLogger (cProcessLogger *)=0
Add instance of process logger to the scheduler.
virtual void printUnblocked ()=0
Prints at once all processes that may have become unblocked asynchronously.
Member Function Documentation
void cScheduler::addLogger (FILE *) [pure virtual]
The kernel passes a file stream pointer for the scheduler to print trace info such as blocking/unblocking events.
Parameters:
FILE* File stream for trace log
See also:
initLog(const char* filename)
getStream()
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::cKernel().
void cScheduler::addProcess (ProcessInfo *) [pure virtual]
After this is called, the kernel core no longer keeps track of the given process. Once the process is created and deemed ready by the kernel it is handed off here. The scheduler is then in charge of state transitions when the kernel gives it appropriate notifications.
Implementation Requirements:
Store the process in some location. It should be recognized as ready given its location but the datastructures and organization are implementation specific.
Parameters:
ProcessInfo* Process to add under scheduler's control
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::initProcess().
void cScheduler::addProcLogger (cProcessLogger *) [pure virtual]
The kernel passes this pointer so the scheduler can update process info upon process addition, state change and termination. This updates the information presented to the top process.
Parameters:
cProcessLogger* Process logger class
See also:
cProcessLogger
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::cKernel().
ProcessInfo * cScheduler::getNextToRun () [pure virtual]
After this function is called, it should be assumed by any scheduler implementation that the kernel will run the given process (unless otherwise notified). The currently running process should implicitly be considered for running next (again).
If there are processes left but all are blocked. This function should block until it receives a signal that a process is unblocked.
Implementation Requirements:
Call printUnblocked() to update the trace log after a clock step.
Block if there are > 0 processes but none can run.
A process listed as running within the scheduler should be treated as ready when this method is called.
A process returned as the 'next to run' should be marked as being in a running state before returning.
If there are no more remaining processes this should return NULL.
Returns:
ProcessInfo* Ready process to run next. May be the same as the currenlty running one.
Warning:
Must be thread safe with block and unblock methods.
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::boot().
void cScheduler::initProcScheduleInfo (ProcessInfo *) [pure virtual]
This method is called after the kernel has initialized all process data but before it is marked ready. This gives the scheduler an oportunity to initialize any scheduler specific data and assign it to the ProcessInfo::scheduleData member.
Implementation Requirements:
No required actions.
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::initProcess().
pidType cScheduler::numProcesses () [pure virtual]
This returns how many processes, both running and blocked, are being handled by the scheduler.
Implementation Requirements:
Return how many processes, running and blocked, are in the scheduler.
Returns:
pidType
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::boot(), and cKernel::cKernel().
void cScheduler::printUnblocked () [pure virtual]
This method is needed to avoid mixed output in the trace logger.
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
void cScheduler::removeProcess (ProcessInfo *) [pure virtual]
When a process terminates, either through normal means or an exception, the kernel will call this function to release a process from the scheduler's control. The scheduler should clean up any internal state for the process. Deallocation of process resources is left to the kernel.
Implementation Requirements:
Scheduler should deallocate any resources it assigned to the process within the ProcessInfo::scheduleData member.
The Scheduler should remove any pointers to the give process to avoid dereferncing a dead pointer.
Implementations must not deallocate any memory except that mentioned above. This is handled by the kernel.
Implementations should mark the process as terminated.
Parameters:
ProcessInfo* Process to remove from scheduler
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::cleanupProcess().
void cScheduler::setBlocked (ProcessInfo *) [pure virtual]
The kernel will call the scheduler with this function when the process has done an operation which causes it to block (I).
Implementation Requirements:
Process must be marked blocked and scheduler state should be changed accordingly.
After this call a process should not be considered for a scheduling decision
Warning:
Must be thread safe. Signal handler/s may block during schedule decision.
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
Referenced by cKernel::boot().
void cScheduler::unblockProcess (ProcessInfo *) [pure virtual]
When a process has completed a blocking call the kernel will notify the scheduler that it should be unblocked. This operation should be very fast since it will likely be called from a signal handler.
Implementation Requirements:
The process must be unblocked and marked ready. It must be available for scheduling with the next call to ::getNextToRun
Parameters:
ProcessInfo* Process to unblock
Warning:
Must be thread safe. Signal handler/s may unblock during schedule decision.
Implemented in cMultiLevel, cLottery, cRoundRobin, and cFCFS.
The documentation for this class was generated from the following file:
include/scheduler/scheduler.h