5103 Project 2: cPRLruApprox Class Reference
cPRLruApprox Class Reference
LRU approximate PR Policy.
#include <pr_lruApprox.h>
Public Member Functions
cPRLruApprox (cFrameAllocPolicy &_FAPolicy)
const char * name ()
Name of PR module.
ePRStatus resolvePageFault (sProc *proc, uint32_t page)
If no frames are free, spill the frame that has the lowest shifted time.
void finishedQuanta (sProc *proc)
Update the approx time field in software.
void finishedIO (sProc *proc, sPTE *page)
I/O is finished so add the PTE to the pageHist so we know what frames are in use.
bool clearPages (int numPages)
Clears pages by sorting the pageHist by the time field (increasing).
void unpinFrame (uint32_t frame)
This is typically called after ::finishedIO so that the PR module unpins the frame in the frame allocation module.
void returnFrame (uint32_t frame)
Return a frame to the system.
Private Member Functions
void updateTime ()
Updates the time field by first shifting the time field to the right and then adding a 1 in the far left position if the ref bit is set.
sPTEOwner * getPTEOwner ()
Get a struct for holding both the PTE and Owner.
void returnPTEOwner (sPTEOwner *pteOwner)
Add a PTEOwner to the pteowner_cache to use later.
Private Attributes
list< sPTEOwner * > pageHist
queue< sPTEOwner * > pteowner_cache
cFrameAllocPolicy & FAPolicy
uint32_t PTSize
Member Function Documentation
bool cPRLruApprox::clearPages (int numPages) [virtual]
Then removes numPages from the front of pageHist.
Implements cPRPolicy.
sPTEOwner * cPRLruApprox::getPTEOwner () [private]
If the pteowner_cache has an entry, re-use it. Otherwise malloc a new one. This helps with heap performance.
Referenced by finishedIO().
const char* cPRLruApprox::name () [inline, virtual]
This is only used for logging purposes so that the PR module can be easily identified.
Implements cPRPolicy.
ePRStatus cPRLruApprox::resolvePageFault (sProc * proc, uint32_t page) [virtual]
This aging algorithm simulates LRU.
Implements cPRPolicy.
void cPRLruApprox::returnFrame (uint32_t frame) [virtual]
The VMM core calls this when a process termintates to free up any of its used frames. This call could be made directly to the frame allocator but using the PR module as a middle man gives it a chance to update as needed.
Implements cPRPolicy.
cPRLruApprox::updateTime () [private]
This function is called on a page fault or after a quanta is finished.
Referenced by finishedQuanta(), and resolvePageFault().
The documentation for this class was generated from the following files:
include/Policy/pr_lruApprox.h
src/Policy/pr_lruApprox.cpp