5103 Project 2: cCPU Class Reference
cCPU Class Reference
Very Simple CPU.
#include <cpu.h>
Public Member Functions
void addVC (int *VC)
Give the cpu a reference to the core's VC.
void switchProc (sProc *)
Context switch for this process.
uint32_t getFaultPage ()
Get the page number that faulted.
uint8_t run ()
Start executing the current process.
Private Member Functions
void incVC (int amnt)
Increment the VC and print its value to trace file.
Private Attributes
sProc * curProc
cMMU mmu
string opCode
string addr
int instr_time
int cs_time
int quanta
int * VC
Detailed Description
This cpu is only used to abstract the actual reading/execution of the programs and the use of the MMU. This cpu is not meant to mimic the functionality of the cpu from the first project.
Member Function Documentation
cCPU::addVC (int * VC)
The VMM core calls this to provide a reference to the VC so the cpu can update it appropriately. This makes it easier than having some back and forth time management between the two systems.
Referenced by cVMM::cVMM().
cCPU::getFaultPage ()
On a page fault the VMM core will queury here to find out which page needs to be brough in. This function simply calls the mmu for this information.
Referenced by cVMM::start().
cCPU::run ()
Once a process has been switched onto the cpu this is called to start execution. The process executes for the quanta specified in the .ini file/s. If the process page faults before this quanta it returns with a special staus code.
Referenced by cVMM::start().
cCPU::switchProc (sProc * newProc)
There are a couple scenarios to consider here:
parameter = NULL - Do Nothing
curProc=NULL Switches process Flushes TLB (Not really necessary but make sure) Set PTBR in MMU
curProc!=NULL Increment CS count for curProc Flush TLB Set PTBR for new proc Increment the VC by the cs_switch time (default 5)
Referenced by cVMM::start().
The documentation for this class was generated from the following files:
include/cpu.h
src/cpu.cpp