5103 Project 2: cVMM Class Reference
cVMM Class Reference
Virtual Memory Manager core class.
#include <vmm_core.h>
Public Member Functions
cVMM (vector< sProc * > &_procs, cPRPolicy &_PRM, cCleanDaemon &_cDaemon)
Virtual Memory Manager Constructor.
~cVMM ()
Virtual Memory Manager Destructor.
sIOContext * pageOut (sProc *, uint32_t, sIOContext *ctx=NULL)
Wrapper for the I/O controller (output scheduling)
sIOContext * pageIn (sProc *, uint32_t, eIOType, sIOContext *ctx=NULL)
Wrapper for I/O controller (input scheduling)
void tickController (int times)
Tick the I/O controller n number of times.
sProc * getProcess (unsigned int id)
Used to get a reference to the particular process struct.
int start ()
Start running the processes.
Private Member Functions
void initProcesses ()
Initialize process data specific to the VMM.
void cleanupProcess (sProc *proc)
Cleanup process data and state.
void clearCircChecks ()
Set the circular fault check flag to false for each proc.
void printResults ()
Gather and print results to log file.
Private Attributes
uint32_t numFrames
Global memory frames.
uint32_t PS
Page size in bytes.
uint32_t PT_Size
Page table size (# of entries)
vector< sProc * > & procs
All processes.
cRoundRobin scheduler
Process scheduler.
int currentProc
PID of current executing process.
cCPU cpu
Executing CPU.
int VC
Virtual Counter.
cIOControl * ioCtrl
I/O Controller.
uint32_t pageInCount
uint32_t pageOutCount
cPRPolicy & PRModule
Page Replacement Module.
cCleanDaemon & cDaemon
Cleaning Daemon.
Constructor & Destructor Documentation
cVMM::cVMM (vector< sProc * > & _procs, cPRPolicy & _PRM, cCleanDaemon & _cDaemon)
Initializes the Virtual Memory Manager class which is the core of the project.
Parameters:
vector<sProc*>& A vector contining the processes loaded in main.cpp. The page tables and other data are initialized during VMM initialization.
cPRPolicy& A reference to a derived class of cPRPolicy (fifo, pure lru, lru apporx).
cCleanDaemon& A reference to the cleaning daemon. This is passed in because it requires a reference to the frame allocation policy which is only available in main.cpp
cVMM::~cVMM ()
Cleans up the VMM.
Member Function Documentation
cVMM::cleanupProcess (sProc * proc) [private]
This function returns all occupied frames back to the system. After this it frees the memory used for the page table.
All other data is left in tact and it is not removed from the process vector because upon termination we need to gather statistics for each process for the results trace.
See also:
cPRPolicy::returnFrame
Referenced by start().
cVMM::clearCircChecks () [private]
This addition ot the cpu is more of a safety net but as long as it is being used it needs to work correctly. This funtion is mainly called after the cleaning daemon clears pages so that the cpu doesn't think there is a circular fault when it was really just the cleaning daemon.
Referenced by start().
cVMM::getProcess (unsigned int id)
In some places like the PR module or the io_controller there is sometimes a need to get a reference to the process when all you have is a pid.
Referenced by cPRFifo::clearPages(), cPRLruApprox::clearPages(), cPRLru::clearPages(), cPRFifo::resolvePageFault(), cPRLru::resolvePageFault(), and cPRLruApprox::resolvePageFault().
cVMM::initProcesses () [private]
The main purpose of this function is to initialize the page table for all processes.
See also:
sProc
Referenced by cVMM().
cVMM::pageIn (sProc * proc, uint32_t page, eIOType iotype, sIOContext * ctx = NULL)
Another wrapper for the I/O controller.
See also:
cIOControl::scheduleIO
Referenced by cPRFifo::resolvePageFault(), cPRLruApprox::resolvePageFault(), and cPRLru::resolvePageFault().
cVMM::pageOut (sProc * proc, uint32_t page, sIOContext * ctx = NULL)
This is a wrapper for the I/O controller. Calling this abstracts the actual I/O controller from those who will use it as well as providing a point for the VMM to record paging statistics.
See also:
cIOControl::scheduleIO
Referenced by cPRFifo::clearPages(), cPRLruApprox::clearPages(), cPRLru::clearPages(), cPRFifo::resolvePageFault(), cPRLru::resolvePageFault(), and cPRLruApprox::resolvePageFault().
cVMM::printResults () [private]
After all execution is finished, this function gathers per-process and global data and prints it to a log file. This log can be read normally or used by the python script to build graphs (assuming a .conf is present).
Referenced by start().
cVMM::start ()
After the FMM has been initialized with some processes this is called to start execution.
cVMM::tickController (int times)
This is used for timekeeping. For example, when wwe do a context switch on the cpu it takes 5 units of time but we still need to keep track of the passage of time within other devices which virtually should be running in parallel.
See also:
cIOcontrol::tick
Referenced by cCPU::incVC().
Member Data Documentation
vector<sProc*>& cVMM::procs [private]
Referenced by clearCircChecks(), cVMM(), getProcess(), initProcesses(), printResults(), and start().
The documentation for this class was generated from the following files:
include/vmm_core.h
src/vmm_core.cpp