5103 Project 2: cFrameAllocPolicy Class Reference
cFrameAllocPolicy Class Reference
An abstract class for allocating frames to processes.
#include <frameAlloc.h>
Public Member Functions
void setNumFrames (int frames)
How many frames does the whole system have.
virtual void regProcs (vector< sProc * > &procs)=0
Give the policy module information about processes.
virtual pair< bool, uint32_t > getFrame (sProc *)=0
virtual void returnFrame (uint32_t frame)=0
System is returning a page.
virtual uint32_t checkOpen (bool)=0
virtual bool pin (uint32_t frame)=0
virtual bool unpin (uint32_t frame)=0
Private Member Functions
virtual void printFrames ()=0
Private Attributes
uint32_t numFrames
Detailed Description
The VMM core uses derived classes of this type to decide how many frames to give a process when it is created.
Member Function Documentation
virtual void cFrameAllocPolicy::regProcs (vector< sProc * > & procs) [pure virtual]
Some frame allocation policies may want information regarding particular processes. This is called after construction and it gives the policy a chance to build any necessary datastructures.
Implemented in cFixedAlloc.
virtual void cFrameAllocPolicy::returnFrame (uint32_t frame) [pure virtual]
This could happen on process termination or invocation of the page cleaning daemon.
Implemented in cFixedAlloc.
Referenced by cPRFifo::clearPages(), cPRLruApprox::clearPages(), cPRLru::clearPages(), cPRFifo::returnFrame(), cPRLruApprox::returnFrame(), and cPRLru::returnFrame().
The documentation for this class was generated from the following file:
include/Policy/frameAlloc.h